### ISSUE TITLE
make is failed on gcc 10

### ISSUE THREAD

**Issue by junaruga** [lh3/bwa#275]
Hello,

I am seeing that the bwa latest version 0.7.17 is failed to build on gcc 10.0.1.

```
$ gcc --version
gcc (GCC) 10.0.1 20200311 (Red Hat 10.0.1-0.9)
Copyright (C) 2020 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

My environment is Linux, Fedora 33 x86_64.

```
$ uname -m
x86_64

$ cat /etc/fedora-release  
Fedora release 33 (Rawhide)
```

Here is the log.

```
$ make
...
gcc -g -Wall -Wno-unused-function -O2 -DHAVE_PTHREAD -DUSE_MALLOC_WRAPPERS bwashm.o bwase.o bwaseqio.o bwtgap.o bwtaln.o bamlite.o bwape.o kopen.o pemerge.o maxk.o bwtsw2_core.o bwtsw2_main.o bwtsw2_aux.o bwt_lite.o bwtsw2_chain.o fastmap.o bwtsw2_pair.o main.o -o bwa -L. -lbwa -lm -lz -lpthread -lrt
/usr/bin/ld: ./libbwa.a(rope.o):/builddir/build/BUILD/bwa-0.7.17/rle.h:33: multiple definition of `rle_auxtab'; ./libbwa.a(bwtindex.o):/builddir/build/BUILD/bwa-0.7.17/rle.h:33: first defined here
/usr/bin/ld: ./libbwa.a(rle.o):/builddir/build/BUILD/bwa-0.7.17/rle.h:33: multiple definition of `rle_auxtab'; ./libbwa.a(bwtindex.o):/builddir/build/BUILD/bwa-0.7.17/rle.h:33: first defined here
collect2: error: ld returned 1 exit status
make: *** [Makefile:30: bwa] Error 1
```

Could you fix it?
Thank you.

**Comment by junaruga** [comment]
I could build by removing the `rle_auxtab` line in `rle.h`.
This is gcc 10 specific. It does not happen on gcc 9.

```
$ git diff
diff --git a/rle.h b/rle.h
index 0d59484..c66b8cb 100644
--- a/rle.h
+++ b/rle.h
@@ -30,8 +30,6 @@ extern "C" {
  *** 43+3 codec ***
  ******************/
 
-const uint8_t rle_auxtab[8];
-
 #define RLE_MIN_SPACE 18
 #define rle_nptr(block) ((uint16_t*)(block))
```

**Comment by jmarshall** [comment]
This is PR #267.

**Comment by lh3** [comment]
Thanks.

**Comment by keiranmraine** [comment]
@lh3 would be nice to get a bugfix release for this

**Comment by HyunK3507** [comment]
Is the problem resolved? After confirming that the problem occurred in GCC version 10 or higher, we downgraded GCC version to 9 or lower. 
https://gist.github.com/jlblancoc/99521194aba975286c80f93e47966dc5
